#!/usr/bin/perl -w
#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-inventory-update event
#

event_actions('nethserver-inventory-update', qw(
    initialize-default-databases        00
));


#
# nethserver-subscription-save event
#

event_templates('nethserver-subscription-save', qw(
    /etc/cron.daily/nethserver-inventory
));

event_actions('nethserver-subscription-save', qw(
    nethserver-inventory-send        30
));

